{{ define "migration" }}
/******************* Code generated by a tool *******************/
/************************ MySQL migration ***********************/
{{ template "create_table" . }}
{{ template "primary-key" . }}
{{ template "primary-key-auto" . }}
{{ template "fks" .}}
{{ template "fks-idx" .}}
{{ template "unique" .}}
/************************ counter {{ c1g }} ***********************/
/************************ counter {{ leftPad c1g 2  }} ***********************/
/************************ MySQL migration ***********************/
{{- end -}}