{{ define "rollback" }}
/******************* Code generated by a tool *******************/
/************************  MySql rollback  **********************/
{{ template "unique-rollback" . }}
{{ template "fks-idx-rollback" . }}
{{ template "fks-rollback" . }}
{{ template "primary-key-rollback" . }}
{{ template "primary-key-auto-rollback" . }}
{{ template "create_table_rollback" . }}
/************************  MySql rollback  **********************/
{{- end -}}